window.tyrano_lang = {
    word: {
    go_title: "这将返回标题页面。确定要继续吗？",
    exit_game: "这将关闭窗口，退出游戏。确定要继续吗？",
    not_saved: "尚无已保存的数据。",
    confirm: "确认",
    confirm_beforeunload: "尚有未保存的内容。确定要退出游戏吗？",
    tag: "标签",
    not_exists: "不存在。",
    error: "发生错误，请检查脚本。",
    label: "文本标签",
    label_double: "在同一场景文件中重复出现。",
    error_occurred: "发生错误。",
    save_file_violation_1: "检测到存档数据发生移动。如果数据并非来自可信来源，请绝对不要加载。",
    save_file_violation_2: "您确定要载入存档并开始游戏吗？",
    save_file_violation_3: "启动已取消。请删除存档数据，然后尝试再次启动应用程序。",
    double_start: "游戏已在运行，无法同时再启动第二个窗口。",
    reload: "重新加载",
    line: "第{ line }行",
    initialized_saved_data: "已重置存档进度。",
    initializing_saved_data: "这将重置存档进度。确定要继续吗？",
    saved_data_is_corrupted: "存档数据可能已损坏。是否要初始化存档数据？",
    save_does_not_work: "保存功能无法在此环境中正常工作，可能是由于在本地运行该应用程序等情况导致的。",
    undefined_tag: "标签“{ name }”不存在。",
    undefined_label: "文本标签“{ name }”不存在。",
    undefined_character: "指定的角色“{ name }”未定义。请使用[chara_new]对其进行定义。",
    undefined_face: "指定角色“{ name }”的表情“{ face }”未定义。请使用[chara_face]进行定义。",
    undefined_character_parts: "指定角色“{ name }”的变体部件未定义。请使用[chara_layer]对其进行定义。",
    undefined_keyframe: "指定的关键帧动画“{ keyframe }”未定义。请使用[keyframe]对其进行定义。",
    undefined_3d_model: "指定的3D模型“{ name }”未定义。",
    preload_failure_sound: "未找到音频文件“{ src }”。请确保您使用了完整路径。\n\n（例如：./data/bgm/my_bgm.mp3）",
    preload_failure_image: "未找到图像文件“{ src }”。请确保您使用了完整路径。\n\n（例如：./data/image/my_image.png）",
    preload_failure_video: "未找到视频文件“{ src }”。请确保您使用了完整路径。\n\n（例如：./data/video/my_video.mp4）",
    invalid_keyframe: "关键帧的值无效。",
    invalid_keyframe_percentage: "为关键帧设置的百分比“{ percentage }”值无效。请将其指定为“0%”、“30%”等。",
    error_in_iscript: "[iscript]中发生错误。",
    missing_endif: "[if]后缺少[elsif]、[else]或[endif]，或[if]中包含过多的标签。",
    missing_endmacro: "[macro]后缺少[endmacro]，或[macro]中包含过多的标签。",
    missing_endignore: "[ignore]后缺少[endignore]，或[ignore]中包含过多的标签。",
    missing_parameter: "标签“{ tag }”需要参数“{ param }”。",
    if_and_endif_do_not_match: "[if]与[endif]数量不一致。",
    unsupported_extensions: "不支持“{ ext }”的文件格式。",
    undefined_keyconfig: "按键配置未定义。可能是因为不存在KeyConfig.js文件，或该文件内存在语法错误。请检查是否遗漏了逗号\",\"、方括号\"]\"或花括号\"}\"。",
    compensate_missing_quart: "检测到异常的\"]\"。可能是因为参数缺失了对应数量的引号，系统将自动进行修正并解析。\n\n修正前：{ before }\n修正后：{ after }",
    duplicate_label: "文本标签“{ name }”在同一场景文件中重复出现。请确保同一场景文件中的文本标签名不重复。",
    file_not_found: "未找到文件。\n\n{ path }",
    patch_not_found: "未找到补丁文件。\n\n{ path }",
    new_patch_found: "发现新版本。\n\nVer: { version }\n{ message }\n\n是否进行更新？",
    apply_web_patch: "即将进行更新。更新完成后，游戏将自动关闭。",
    apply_patch_complete: "更新已完成，请重启游戏。",
    },

    novel: {
        file_menu_button_save: "menu_button_save.gif",
        file_menu_button_load: "menu_button_load.gif",
        file_menu_button_message_close: "menu_message_close.gif",
        file_menu_button_skip: "menu_button_skip.gif",
        file_menu_button_title: "menu_button_title.gif",
        file_menu_button_close: "menu_button_close.png",
        file_menu_bg: "menu_bg.jpg",
        file_save_bg: "menu_save_bg.jpg",
        file_load_bg: "menu_load_bg.jpg",
        file_button_menu: "button_menu.png",
        error_occurred: "error occurred",
    },
};
